[package]
name = "brc20_finance"
version = "0.1.0"
edition = "2021"

[dependencies]
db = { path = "db" }
server = { path = "server" }

[workspace]
members = [ ".", "db", "server" ]

[profile.release]
debug = true
