[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
revm = "19.4.0"
rlimit = "0.10.2"
rocksdb = "0.23.0"
rs_merkle = "1.4.2"
serde = { version = "1.0.217", features = ["derive"] }
serde-hex = "0.1.0"
serde_json = "1.0.138"

[dev-dependencies]
tempfile = "3.16.0"
